### ISSUE TITLE
Recommended default SE method for aftsrr?

### ISSUE THREAD

**Issue by jarbet** [stc04003/aftgee#7]
I am wondering what standard error (`SE`) method you recommend for `aftsrr` by default?

I see the following paper seems to recommend a more computationally efficient modified multiplier bootstrap method - do any of the SE options implement this?

Chiou, S., Sangwook Kang, and Jun Yan. "Rank‐based estimating equations with general weight for accelerated failure time models: an induced smoothing approach." Statistics in Medicine 34.9 (2015): 1495-1510.

**EDIT**: after reading your JSS paper, I think the fast modified multiplier bootstrap option that you seemed to recommend is `ISMB`, right?

**Comment by stc04003** [comment]
Yes, ISMB provides a good balance between speed and performance.

**Comment by jarbet** [comment]
> Yes, ISMB provides a good balance between speed and performance.

Got it, thanks!
